spring.application.name=contas-mensais

spring.datasource.url=jdbc:postgresql://db:5432/contasmensais
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.devtools.restart.poll-interval=2s
spring.devtools.restart.quiet-period=1s
